FROM node:18-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential python3

COPY front-end/package*.json ./
RUN npm install

COPY front-end/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
