version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/app
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/secure-chat

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
